export default {
  default: {
    fc: 'f-form-control',
    ig: 'f-input-group',
    iga: 'f-input-group-addon',
    igb: 'f-input-group-btn',
    he: 'f-has-error',
    btn: 'f-btn',
    bd: 'f-btn-secondary',
    bs: 'f-btn-success',
    btnSm: 'f-btn-sm',
    btnLg: 'f-btn-lg',
    submit: 'f-submit',
    hf: 'f-has-feedback',
    cl: 'f-control-label',
  },
  bootstrap3: {
    fc: 'form-control',
    ig: 'input-group',
    iga: 'input-group-addon',
    igb: 'input-group-btn',
    he: 'has-error',
    btn: 'btn',
    bd: 'btn-default',
    bs: 'btn-success',
    btnSm: 'btn-sm',
    btnLg: 'btn-lg',
    hf: 'has-feedback',
    cl: 'control-label',
  },
  bootstrap4: {
    fc: 'form-control',
    ig: 'input-group',
    iga: 'input-group-addon',
    igb: 'input-group-btn',
    he: 'has-danger',
    ie: 'is-invalid',
    btn: 'btn',
    bd: 'btn-default',
    bs: 'btn-success',
    btnSm: 'btn-sm',
    btnLg: 'btn-lg',
    hf: 'f-has-feedback',
    // cl: 'col-form-label'
  },
  foundation6: {
    ig: 'input-group',
    igi: 'input-group-field',
    iga: 'input-group-label',
    igb: 'input-group-button',
    he: 'has-error',
    ie: 'is-invalid-input',
    le: 'is-invalid-label',
    btn: 'button',
    bs: 'success',
    btnSm: 'small',
    btnLg: 'large',
    hf: 'f-has-feedback',
  },
}
