export default {
  options: {
    methods: ['card'],
    ibank: [],
    emoney: [],
    cash: [],
    fast: [],
    card_icons: ['mastercard', 'visa'],
    title: '',
    button: true,
    full_screen: true,
    tooltip: true,
    email: false,
    fields: false,
    link: '',
    offer: '',
    locales: [],
    messages: {},
    api_domain: 'api.fondy.eu',
    fee: true,
    customer_fields: [],
    active_tab: 'card',
    logo_url: '',
    offerta_url: '',
  },
  popup: {
    append_to: 'body'
  },
  regular: {
    insert: false,
    open: false,
    hide: false,
    period: ['day', 'week', 'month']
  },
  params: {
    merchant_id: 1396424, // 900024 dev, 1396424 prod
    amount: 0,
    amount_with_fee: 0,
    fee: 0, // %
    currency: 'USD',
    recurring_data: {
      period: 'month',
      every: 1,
      start_time: '',
      end_time: '',
      amount: 0,
    },
    card_number: '',
    expiry_date: '',
    cvv2: '',
    email: '',
    code: '',
    order_desc: '',
    offer: false,
    lang: 'en',
    custom: {},
    customer_data: {},
  },
  template: {},
  messages: {},
}
